// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPxQmBUnGwO0zGVw-cY9B9HB2PqjC4b1g',
    appId: '1:114850558410:web:97b708b57bb792cbe21f33',
    messagingSenderId: '114850558410',
    projectId: 'theo-firebase-0204',
    authDomain: 'theo-firebase-0204.firebaseapp.com',
    storageBucket: 'theo-firebase-0204.appspot.com',
    measurementId: 'G-K0H97DV45N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BVoi7QJ5WxL79N48jV4y8Zc-io0t2J0',
    appId: '1:114850558410:android:a6a5bd7ba7854667e21f33',
    messagingSenderId: '114850558410',
    projectId: 'theo-firebase-0204',
    storageBucket: 'theo-firebase-0204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQcLOZiBnDI7OwpL7C_zweSyKYkMmSbk',
    appId: '1:114850558410:ios:fe51ba9bf8e32bb2e21f33',
    messagingSenderId: '114850558410',
    projectId: 'theo-firebase-0204',
    storageBucket: 'theo-firebase-0204.appspot.com',
    iosBundleId: 'com.example.firebaseAula',
  );
}
